### ISSUE TITLE
efi boot file removed from mini iso

### ISSUE THREAD

**Issue by lnussel** [openSUSE/product-builder-plugins#3]
Not sure why this was added:
https://github.com/openSUSE/product-builder-plugins/commit/335132a0b00c4c801a48b0e703d17419e2023c1d
and this removed:
https://github.com/openSUSE/product-builder-plugins/commit/b201a365665a9407143c3b9f30abd514bbb2be19

It leads to unbootable mini iso on UEFI though. /boot/x86_64/efi is needed for that.

**Comment by adrianschroeter** [comment]
solved
