### ISSUE TITLE
mini iso still contains too much

### ISSUE THREAD

**Issue by lnussel** [openSUSE/product-builder-plugins#5]
Mini iso for Leap 15 is about 350MB. https://github.com/openSUSE/product-builder-plugins/commit/335132a0b00c4c801a48b0e703d17419e2023c1d still needs to be reverted.

**Comment by lnussel** [comment]
will be fixed in installation-images: https://bugzilla.suse.com/show_bug.cgi?id=1063789

**Comment by adrianschroeter** [comment]
we agreed to solve this by package splitting
