### ISSUE TITLE
appdata-icons.tar.gz / appdata-ignore.xml.gz / appdata-screenshots.tar are not added to repomd.xml

### ISSUE THREAD

**Issue by fcrozat** [openSUSE/product-builder-plugins#7]
appstream data files are not added to repomd.xml (appdata-screenshots.tar doesn't exist on SLE15 but it exists on TW). 

This means those files aren't downloaded by libzypp despite being present in the repository.

This is breaking gnome-software on SLE15 / Leap15

**Comment by DimStar77** [comment]
- appdata-ignore.xml.gz is merely used for debug - and should not be registered in repomd.xml
- appdata-icons.tar.gz is mandatory (if there is an appdata.xml.gz, there must be an icon-tarball)
- screenshots.tar is optional - I don't think we have a lot of content on TW there neither (it'sonly used for fonts in TW, and only google-roboto seems to work)

**Comment by adrianschroeter** [comment]
these files are not added by the plugins, the plugin just executes /usr/bin/openSUSE-appstream-process, so this code needs to take care.

**Comment by DimStar77** [comment]
Are you sure? What adds appdata.xml.gz to repomd.xml then? /usr/bin/openSUSE-appstream-process clearly does not

**Comment by adrianschroeter** [comment]
On Freitag, 16. März 2018, 14:27:20 CET wrote Dominique Leuenberger:
> Are you sure? What adds appdata.xml.gz to repomd.xml then? /usr/bin/openSUSE-appstream-process clearly does not

I am not aware that any code did that at all in the past ...

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by DimStar77** [comment]
Mus be current code, as

http://download.opensuse.org/distribution/leap/15.0/repo/oss/repodata/repomd.xml

contains:

```
<data type="appdata">
  <checksum type="sha256">216a8552fa734040124bb87aa7c45d43b4ca2d6b1fb57a387964be3ffc956542</checksum>
  <open-checksum type="sha256">329019c2148f3f75c6730e3dc62d999d5866a71d4847bb74ef1a521364081c01</open-checksum>
  <location href="repodata/216a8552fa734040124bb87aa7c45d43b4ca2d6b1fb57a387964be3ffc956542-appdata.xml.gz"/>
  <timestamp>1521063040</timestamp>
  <size>2947600</size>
  <open-size>9898784</open-size>
</data>
```

**Comment by adrianschroeter** [comment]
just for the record, add_product_susedata is doing this.
