### ISSUE TITLE
add_product_susedata  fails

### ISSUE THREAD

**Issue by lnussel** [openSUSE/product-builder-plugins#8]
[ 1758s] Apr-22 11:24:35 <1> : [I] Executing command </usr/bin/add_product_susedata -u -k /usr/src/packages/SOURCES/openSUSE-ftp-ftp-x86_64.kwd -p -e /usr/share/doc/packages/eulas -d /usr/src/packages/KIWIROOT/main/openSUSE-15.0-x86_64-Build213.1-Media1>
[ 1860s] Apr-22 11:26:17 <3> : [E] Called </usr/bin/add_product_susedata -u -k /usr/src/packages/SOURCES/openSUSE-ftp-ftp-x86_64.kwd -p -e /usr/share/doc/packages/eulas -d /usr/src/packages/KIWIROOT/main/openSUSE-15.0-x86_64-Build213.1-Media1> exit status: <255> output: INFO: reading eula data
[ 1860s] INFO: reading repomd.xml
[ 1860s] INFO: reading primary repodata/bdc2e5777d0dc4feed18918aa21023feec1e1acb202199928fe903ec60b5b320-primary.xml.gz
[ 1860s] INFO: processing packages from primary
[ 1860s] INFO: cleanup
[ 1860s] INFO: i18n
[ 1860s] INFO: translate cs
[ 1860s] INFO: add susedata.cs
[ 1860s] INFO: reading /usr/src/packages/KIWIROOT/main/openSUSE-15.0-x86_64-Build213.1-Media1/repodata/susedata.cs.xml.gz
[ 1860s] INFO: translate de
[ 1862s] 
[ 1862s] typhoon1 failed "build openSUSE-ftp-ftp-x86_64.kiwi" at Sun Apr 22 11:26:19 UTC 2018.

**Comment by adrianschroeter** [comment]
you have an outdated inst-source-utils package in Leap:15.0
